### ISSUE TITLE
[Feature Request] Disable investigational use popup

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/ViewersV3#61]
### What feature or change would you like to see made?

Remove the popup below. Since IDC instance of the viewer can only be used with the images in IDC, which are not applicable for clinical use, this popup is redundant, while it in some cases obscures other messages.

<img width="531" alt="image" src="https://github.com/user-attachments/assets/7683b628-2020-4d5c-9eab-4778da5ea621">

### Why should we prioritize this feature?

Discussed and agreed this should be done at the IDC coordination meeting

**Comment by igoroctaviano** [comment]
I'll let Bill know that he needs to update IDC config / include this:
```
  investigationalUseDialog: {
    option: 'never',
  },
  ```
